# Generated by Django 2.2.6 on 2020-05-15 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='datatest',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
