# Generated by Django 2.2.6 on 2020-05-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnaapi', '0002_users_datatest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='datatest',
            new_name='buy',
        ),
        migrations.AddField(
            model_name='users',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
